# Generated by Django 4.0.4 on 2022-04-14 00:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import zezere.models


class Migration(migrations.Migration):

    dependencies = [
        ('zezere', '0012_auto_20200323_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sshkey',
            name='title',
            field=models.CharField(blank=True, max_length=10, verbose_name='SSH title'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^([0-9A-F]{2}[:]){5}([0-9A-F]{2})$'), zezere.models.validator_disallow_blacklisted_mac], verbose_name='Device MAC Address'),
        ),
    ]
